books/urls.py
from django.contrib import admin
from django.urls import path

from books import views
from books.views import CategoryCreateView, CategoryListView, CategoryUpdateView, CategoryDeleteView, \
    CategoryDetailView, HomeTemplateView, PromotionCreateView, \
    PromotionListView, PromotionUpdateView, PromotionDeleteView, PromotionDetailView, BookCreateView, BookListView, \
    BookUpdateView, BookDeleteView, BookDetailView, AuthorCreateView, AuthorListView, AuthorUpdateView, \
    AuthorDeleteView, AuthorDetailView, AuthorBookCreateView, AuthorBookListView, AuthorBookDeleteView, \
    AuthorBookDetailView, AuthorBookUpdateView, PublisherCreateView, PublisherListView, PublisherUpdateView, \
    PublisherDeleteView, PublisherDetailView, PublisherBookCreateView, PublisherBookListView, \
    PublisherBookUpdateView, PublisherBookDeleteView, PublisherBookDetailView, AboutTemplateView, CartListView, \
    CartDetailView

app_name = 'books'


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home_page'),
    path('about/', AboutTemplateView.as_view(), name='about_page'),

    path('category-create/', CategoryCreateView.as_view(), name='category_create'),
    path('category-list/', CategoryListView.as_view(), name='category_list'),
    path('category-update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
    path('category-detail/<int:pk>', CategoryDetailView.as_view(), name='category_detail'),

    path('promotion-create/', PromotionCreateView.as_view(), name='promotion_create'),
    path('promotion-list/', PromotionListView.as_view(), name='promotion_list'),
    path('promotion-update/<int:pk>', PromotionUpdateView.as_view(), name='promotion_update'),
    path('promotion-delete/<int:pk>', PromotionDeleteView.as_view(), name='promotion_delete'),
    path('promotion-detail/<int:pk>', PromotionDetailView.as_view(), name='promotion_detail'),

    path('books-create/', BookCreateView.as_view(), name='books_create'),
    path('books-list/', BookListView.as_view(), name='books_list'),
    path('books-update/<int:pk>', BookUpdateView.as_view(), name='books_update'),
    path('books-delete/<int:pk>', BookDeleteView.as_view(), name='books_delete'),
    path('books-detail/<int:pk>', BookDetailView.as_view(), name='books_detail'),

    path('authors-create/', AuthorCreateView.as_view(), name='authors_create'),
    path('authors-list/', AuthorListView.as_view(), name='authors_list'),
    path('authors-update/<int:pk>', AuthorUpdateView.as_view(), name='authors_update'),
    path('authors-delete/<int:pk>', AuthorDeleteView.as_view(), name='authors_delete'),
    path('authors-detail/<int:pk>', AuthorDetailView.as_view(), name='authors_detail'),

    path('authors-books-create/', AuthorBookCreateView.as_view(), name='authors_books_create'),
    path('authors-books-list/', AuthorBookListView.as_view(), name='authors_books_list'),
    path('authors-books-update/<int:pk>', AuthorBookUpdateView.as_view(), name='authors_books_update'),
    path('authors-books-delete/<int:pk>', AuthorBookDeleteView.as_view(), name='authors_books_delete'),
    path('authors-books-detail/<int:pk>', AuthorBookDetailView.as_view(), name='authors_books_detail'),

    path('publishers-create/', PublisherCreateView.as_view(), name='publishers_create'),
    path('publishers-list/', PublisherListView.as_view(), name='publishers_list'),
    path('publishers-update/<int:pk>', PublisherUpdateView.as_view(), name='publishers_update'),
    path('publishers-delete/<int:pk>', PublisherDeleteView.as_view(), name='publishers_delete'),
    path('publishers-detail/<int:pk>', PublisherDetailView.as_view(), name='publishers_detail'),

    path('publishers-books-create/', PublisherBookCreateView.as_view(), name='publishers_books_create'),
    path('publishers-books-list/', PublisherBookListView.as_view(), name='publishers_books_list'),
    path('publishers-books-update/<int:pk>', PublisherBookUpdateView.as_view(), name='publishers_books_update'),
    path('publishers-books-delete/<int:pk>', PublisherBookDeleteView.as_view(), name='publishers_books_delete'),
    path('publishers-books-detail/<int:pk>', PublisherBookDetailView.as_view(), name='publishers_books_detail'),

    path('orders-list/', CartListView.as_view(), name='orders_list'),
    path('orders-detail/<int:pk>', CartDetailView.as_view(), name='orders_detail'),

    path('open_cart/', views.open_cart_view, name="open_cart"),
    path('add_product_to_cart/', views.add_product_to_cart, name="add_product_to_cart"),
    path('checkout/', views.checkout_view, name="checkout"),
]

my_library_django_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from my_library_django_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('books.urls')),
    path('users/', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/promotion/promotion_create.html
{% extends 'base.html' %}
{% block title %}
    Promotion Create
{% endblock %}
{% block content %}
    <div class="p-3"><a href='{% url 'books:promotion_list' %}' class="btn btn-primary btn-lg">
        Back to List
    </a></div>
    <div class="container p-3 my-3 border border-info">
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info">Save</button>
        </form>
    </div>
{% endblock %}

templates/promotion/promotion_delete.html
{% extends 'base.html' %}
{% block title %}
    Delete Promotion
{% endblock %}
{% block content %}
    <div class="container p-3 my-3 border border-info">
        <form method="post" action="">
            {% csrf_token %}
            <p class="btn btn-danger">Are you sure, do you want to delete this promotion?</p><br>
            <p class="btn btn-warning">Do you want to give up?</p>
            <p><a href="{% url 'books:promotion_list' %}" class="btn btn-primary btn-lg">Then, go back to the list of
                promotions</a></p>
            <button type="submit" class="btn btn-info">Or, Delete</button>
        </form>
    </div>
{% endblock %}

templates/promotion/promotion_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Promotion Details
{% endblock %}
{% block content %}
    <div class="container-fluid text-center" style="margin-top:30px">
        <h2 class="font-weight-bolder bg-info text-white p-1">{{ promotion.name }}</h2>
    </div>
    <div class="container-fluid text-center" style="margin-top:30px">
        <h2 class="font-weight-bolder bg-info text-white p-1">{{ promotion.period_of_promotion }}</h2>
    </div>
    <br>
    <div class="container-fluid">
        <div class="row">
            {% for book in books %}
                <div class="card m-4" style="width: 18rem;">
                    <a href="{% url 'books:books_detail' book.id %}" style="text-decoration: none">
                        {% if book.image %}
                            <img class="card-img-top border"
                                 src="{{ book.image.url }}"
                                 alt="Card image cap">
                        {% else %}
                            <img class="card-img-top border"
                                 src="{% static 'img/books/no_book_image_available.png' %}"
                                 alt="Card image cap">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title"><strong>{{ book.title }}</strong></h5>
                            <p class="card-text">
                                {% for author_book in authors_books %}
                                    {% if author_book.book == book %}
                                        <strong>{{ author_book.author.name }},</strong>
                                    {% endif %}
                                {% endfor %}
                            </p>
                            <p class="card-text">
                                {% for publisher_book in publishers_books %}
                                    {% if publisher_book.book == book %}
                                        <strong>{{ publisher_book.publisher.name }}</strong>
                                    {% endif %}
                                {% endfor %}
                            </p>
                            <p class="card-text">
                                <strong>
                                    Pret: {{ book.price }} lei
                                </strong>
                            </p>
                            <div class="card-footer">
                                <form method="post" action="{% url 'books:add_product_to_cart' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="book_id" value="{{ book.id }}">
                                    <button class="btn btn-primary m-1" type="submit">ADD TO CART</button>
                                </form>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <a href="{% url 'books:promotion_list' %}" class="btn btn btn-primary">BACK TO LIST</a>
    </div><br>
{% endblock %}

templates/promotion/promotion_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    List of Promotions
{% endblock %}
{% block content %}
    <div class="container container-fluid container-sm text-center">
        <h2 class="p-3"><strong>LISTA DE PROMOTII</strong></h2>
    </div>
    <div class="table-responsive p-3">
        <table class="table table-hover table-info table-striped table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nume Promotie</th>
                <th>Descriere Promotie</th>
                <th>Detalii Promotie</th>
            </tr>
            </thead>
            <tbody>
            {% for promotion in all_promotions %}
                <tr>
                    <td>{{ promotion.id }}</td>
                    <td>{{ promotion.name }}</td>
                    <td>{{ promotion.period_of_promotion }}</td>
                    <td>
                        <a href="{% url 'books:promotion_detail' promotion.id %}"
                           class="btn btn btn-warning">DETAILS</a>
                        <a href="{% url 'books:promotion_list' %}" class="btn btn btn-primary">BACK TO LIST</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="p-3">
        <a href="{% url 'books:promotion_list' %}" class="btn btn-primary btn-lg">BACK TO LIST</a>
        <a href="{% url 'logout' %}" class="btn btn-warning btn-lg">LOGOUT</a>
        <a href="{% url 'books:home_page' %}" class="btn btn-primary btn-lg">TO HOME PAGE</a>
    </div><br>

    {% if current_user and current_user.is_superuser %}
        <div class="p-3"><a href='{% url 'books:promotion_create' %}' class="btn btn-primary btn-lg">
            Add new promotion
        </a></div>
        <div class="table-responsive p-3">
            <table class="table table-hover table-info table-striped table-bordered">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Period of promotion</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for promotion in all_promotions %}
                    <tr>
                        <td>{{ promotion.id }}</td>
                        <td>{{ promotion.name }}</td>
                        <td>{{ promotion.period_of_promotion }}</td>
                        <td>
                            <a href="{% url 'books:promotion_update' promotion.id %}" class="btn btn-info">Update</a>
                            <a href="{% url 'books:promotion_delete' promotion.id %}" class="btn btn-danger">Delete</a>
                            <a href="{% url 'books:promotion_detail' promotion.id %}"
                               class="btn btn-warning">Details</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="p-3">
            <a href="{% url 'logout' %}" class="btn btn-warning btn-lg">Logout</a>
            <a href="{% url 'books:home_page' %}" class="btn btn-primary btn-lg">To home page</a>
        </div><br>
    {% endif %}
{% endblock %}

templates/promotion/promotion_update.html
{% extends 'base.html' %}
{% block title %}
    Update Promotion
{% endblock %}
{% block content %}
    <div class="p-3"><a href="{% url 'books:promotion_list' %}" class="btn btn-primary btn-lg">
        Back to List
    </a></div>
    <div class="container p-3 my-3 border border-info">
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info">
                Update
            </button>
        </form>
    </div>
{% endblock %}