books/urls.py
from django.contrib import admin
from django.urls import path

from books import views
from books.views import CategoryCreateView, CategoryListView, CategoryUpdateView, CategoryDeleteView, \
    CategoryDetailView, HomeTemplateView, PromotionCreateView, \
    PromotionListView, PromotionUpdateView, PromotionDeleteView, PromotionDetailView, BookCreateView, BookListView, \
    BookUpdateView, BookDeleteView, BookDetailView, AuthorCreateView, AuthorListView, AuthorUpdateView, \
    AuthorDeleteView, AuthorDetailView, AuthorBookCreateView, AuthorBookListView, AuthorBookDeleteView, \
    AuthorBookDetailView, AuthorBookUpdateView, PublisherCreateView, PublisherListView, PublisherUpdateView, \
    PublisherDeleteView, PublisherDetailView, PublisherBookCreateView, PublisherBookListView, \
    PublisherBookUpdateView, PublisherBookDeleteView, PublisherBookDetailView, AboutTemplateView, CartListView, \
    CartDetailView

app_name = 'books'


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home_page'),
    path('about/', AboutTemplateView.as_view(), name='about_page'),

    path('category-create/', CategoryCreateView.as_view(), name='category_create'),
    path('category-list/', CategoryListView.as_view(), name='category_list'),
    path('category-update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
    path('category-detail/<int:pk>', CategoryDetailView.as_view(), name='category_detail'),

    path('promotion-create/', PromotionCreateView.as_view(), name='promotion_create'),
    path('promotion-list/', PromotionListView.as_view(), name='promotion_list'),
    path('promotion-update/<int:pk>', PromotionUpdateView.as_view(), name='promotion_update'),
    path('promotion-delete/<int:pk>', PromotionDeleteView.as_view(), name='promotion_delete'),
    path('promotion-detail/<int:pk>', PromotionDetailView.as_view(), name='promotion_detail'),

    path('books-create/', BookCreateView.as_view(), name='books_create'),
    path('books-list/', BookListView.as_view(), name='books_list'),
    path('books-update/<int:pk>', BookUpdateView.as_view(), name='books_update'),
    path('books-delete/<int:pk>', BookDeleteView.as_view(), name='books_delete'),
    path('books-detail/<int:pk>', BookDetailView.as_view(), name='books_detail'),

    path('authors-create/', AuthorCreateView.as_view(), name='authors_create'),
    path('authors-list/', AuthorListView.as_view(), name='authors_list'),
    path('authors-update/<int:pk>', AuthorUpdateView.as_view(), name='authors_update'),
    path('authors-delete/<int:pk>', AuthorDeleteView.as_view(), name='authors_delete'),
    path('authors-detail/<int:pk>', AuthorDetailView.as_view(), name='authors_detail'),

    path('authors-books-create/', AuthorBookCreateView.as_view(), name='authors_books_create'),
    path('authors-books-list/', AuthorBookListView.as_view(), name='authors_books_list'),
    path('authors-books-update/<int:pk>', AuthorBookUpdateView.as_view(), name='authors_books_update'),
    path('authors-books-delete/<int:pk>', AuthorBookDeleteView.as_view(), name='authors_books_delete'),
    path('authors-books-detail/<int:pk>', AuthorBookDetailView.as_view(), name='authors_books_detail'),

    path('publishers-create/', PublisherCreateView.as_view(), name='publishers_create'),
    path('publishers-list/', PublisherListView.as_view(), name='publishers_list'),
    path('publishers-update/<int:pk>', PublisherUpdateView.as_view(), name='publishers_update'),
    path('publishers-delete/<int:pk>', PublisherDeleteView.as_view(), name='publishers_delete'),
    path('publishers-detail/<int:pk>', PublisherDetailView.as_view(), name='publishers_detail'),

    path('publishers-books-create/', PublisherBookCreateView.as_view(), name='publishers_books_create'),
    path('publishers-books-list/', PublisherBookListView.as_view(), name='publishers_books_list'),
    path('publishers-books-update/<int:pk>', PublisherBookUpdateView.as_view(), name='publishers_books_update'),
    path('publishers-books-delete/<int:pk>', PublisherBookDeleteView.as_view(), name='publishers_books_delete'),
    path('publishers-books-detail/<int:pk>', PublisherBookDetailView.as_view(), name='publishers_books_detail'),

    path('orders-list/', CartListView.as_view(), name='orders_list'),
    path('orders-detail/<int:pk>', CartDetailView.as_view(), name='orders_detail'),

    path('open_cart/', views.open_cart_view, name="open_cart"),
    path('add_product_to_cart/', views.add_product_to_cart, name="add_product_to_cart"),
    path('checkout/', views.checkout_view, name="checkout"),
]

my_library_django_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from my_library_django_app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('books.urls')),
    path('users/', include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    About
{% endblock %}
{% block content %}
    <div class="container-fluid" style="margin:30px">
        <h1><strong><img src="{% static 'img/logo/poza_1.jpg' %}" alt="LIBRARIA MEA" width="450" height="200">BINE ATI
            VENIT LA "PRIMA MEA
            LIBRARIE.NET"</strong></h1>
        <h2><strong>AICI VETI GASI CELE MAI INTERESANTE CARTI PENTRU PRIMA DUMNEAVOASTRA BIBLIOTECA:<br>
            „Oameni obișnuiți au televizoare mari, oamenii extraordinari au biblioteci mari.“ Robin Sharma, orator
            motivațional de mare succes
        </strong></h2>
        <h3><strong>DESPRE NOI</strong></h3>
        <h4><strong>Prima mea librarie online - SRL</strong></h4>
        <h4><strong>Adresa: Bdul Basarabiei - 45; Bucuresti - Romania</strong></h4>
        <h4><strong>Telefon: 0745-123789</strong></h4>
        <h4><strong>E-mail: primamealibrarie.net</strong></h4>
        <h4><strong>Program relații cu clienții: Luni - Vineri: 9:00 - 20:00 Sâmbătă - Duminică: 10:00 - 18:00.</strong>
        </h4>
        <h4><strong>primamealibrarie.net este un proiect al companiei 'Prima mea librarie online - SRL' lansat in martie
            2021.</strong></h4>
        <h4><strong>Proiectul se doreste a fi o librarie on-line care sa ofere carti de calitate, pentru toate gusturile
            si pentru toate varstele.</strong></h4>
        <h4><strong>Libraria este structurata in doua mari categorii: Stiinte si Beletristica, care contin in total 24
            de subcategorii, dar va lasam sa le explorati singuri.</strong></h4>
        <h4><strong>Speram sa aveti o experienta culturala placuta alaturi de noi in urmatorii ani.</strong></h4>
    </div>
    <div class="container-fluid" style="margin:30px">
        <nav>
            <br><a href="{% url 'login' %}" class="btn btn-primary btn-lg">TO PAGE LOGIN</a>
            <a href="{% url 'logout' %}" class="btn btn-warning btn-lg">LOGOUT</a>
            <a href="{% url 'books:home_page' %}" class="btn btn-primary btn-lg">TO HOME PAGE</a>
        </nav>
        <br>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% block header %}
    <div class="jumbotron jumbotron-fluid" style="margin-bottom:0; background-image:url('https://mdbootstrap.com/img/new/standard/nature/111.jpg'); background-size:cover;">
        <div class="container-fluid bg-info text-center font-weight-bolder">
            <h1 class="font-weight-bolder bg-info text-white text-center p-2" style="font-size: 50px;">PRIMA MEA
                LIBRARIE.NET</h1>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg bg-info navbar-dark text-white">
        <a href="{% url 'books:home_page' %}" class="large_white_text m-2"
           style="font-size: 30px; text-decoration: none;">PRIMA
            MEA LIBRARIE.NET</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link large_white_text" href="{% url 'books:about_page' %}">ABOUT</a>
                </li>
                <li class="nav-item active dropdown">
                    <a class="nav-link dropdown-toggle large_white_text" href="#"
                       id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">STORE</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'books:category_list' %}">TOATE CATEGORIILE</a>
                        <a class="dropdown-item" href="{% url 'books:promotion_list' %}">TOATE PROMOTIILE</a>
                    </div>
                </li>
                {% for main_category in categories %}
                    {% if not main_category.parent_category %}
                        <li class="nav-item active dropdown">
                            <a class="nav-link dropdown-toggle large_white_text" href="#" id="navbarDropdownMenuLink"
                               role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ main_category.name }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                {% for sub_category in categories %}
                                    {% if sub_category.parent_category == main_category %}
                                        <a class="dropdown-item"
                                           href="{% url 'books:category_detail' sub_category.id %}">{{ sub_category.name }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if current_user and current_user.is_superuser %}
                    <li class="nav-item active dropdown">
                        <a class="nav-link dropdown-toggle large_white_text" href="#"
                           id="navbarDropdownMenuLink" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ADMIN</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'books:category_list' %}">TOATE CATEGORIILE</a>
                            <a class="dropdown-item" href="{% url 'books:books_list' %}">TOATE CARTILE</a>
                            <a class="dropdown-item" href="{% url 'books:promotion_list' %}">TOATE PROMOTIILE</a>
                            <a class="dropdown-item" href="{% url 'books:authors_list' %}">TOTI AUTORII</a>
                            <a class="dropdown-item" href="{% url 'books:publishers_list' %}">TOATE EDITURILE</a>
                            <a class="dropdown-item" href="{% url 'books:authors_books_list' %}">TOATE CARTILE SI
                                AUTORII</a>
                            <a class="dropdown-item" href="{% url 'books:publishers_books_list' %}">TOATE CARTILE SI
                                EDITURILE</a>
                            <a class="dropdown-item" href="{% url 'books:orders_list' %}">TOATE COMENZILE</a>
                            <a class="dropdown-item" href="http://127.0.0.1:8000/admin/users/extenduser/add/">CREARE USER</a>
                            <a class="dropdown-item" href="http://127.0.0.1:8000/admin/">ADMIN PANEL</a>
                        </div>
                    </li>
                {% endif %}
                <li class="nav-item  active">
                    <a class="nav-link large_white_text" href="{% url 'login' %}"><i class="fas fa-user fa-lg"
                                                                                     style="color: white"></i></a>
                </li>
                <li class="nav-item  active">
                    <a class="nav-link large_white_text" href="{% url 'books:open_cart' %}"><i
                            class="fas fa-shopping-cart fa-lg"
                            style="color: white"></i><span class="rounded-pill small font-weight-bolder"
                                                           style="background: white; color: #003366">  {{ count }}  </span>
                    </a>
                </li>
                {% if current_user and not current_user.is_anonymous %}
                    <li class="nav-item  active">
                        <a class="nav-link large_white_text" href="{% url 'logout' %}">LOGOUT</a>
                    </li>
                {% endif %}
            </ul>
            <form class="form-inline" action="">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" id="myInput">
                <button class="btn bg-info search_text" type="submit" style="color: white">SEARCH</button>
            </form>
        </div>
    </nav>
{% endblock %}

{% block content %}
{% endblock %}

<!-- Footer -->
<footer class="page-footer font-small bg-info">
    <!-- Footer Elements -->
    <div class="container">
        <!-- Grid row-->
        <div class="row">
            <!-- Grid column -->
            <div class="col-md-12 py-4">
                <span class="py-3 text-white"><a href="{% url 'books:home_page' %}"
                                                 style="text-decoration: none">Home  </a></span>
                <span class="py-3 text-white"><a href="{% url 'books:about_page' %}" style="text-decoration: none">About us</a></span><br>
                <span class="py-3 text-white">Location:</span>
                <span class="py-3 text-white">Bucuresti - Romania</span><br>
                <span class="py-3 text-white">Bdul Basarabiei - 45  </span><br>
                <span class="py-3 text-white">Contact Us:  </span>
                <span class="py-3 text-white"><i class="fa fa-phone mr-3 text-white"></i>0745-123789</span><br>
                <span class="py-3 text-white"><a href="https://primamealibrarie.net/" style="text-decoration: none">primamealibrarie.net</a></span><br>
                <span class="py-3 text-white">Program relații cu clienții:</span>
                <span class="py-3 text-white">Luni - Vineri: 9:00 - 20:00</span>
                <span class="py-3 text-white">Sâmbătă - Duminică: 10:00 - 18:00</span>
                <hr style="background: white">
                <div class="mb-5 flex-center text-center">
                    <!-- Facebook -->
                    <a class="fb-ic btn btn-primary btn-lg btn-floating" style="background: white"
                       href="https://www.facebook.com">
                        <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: mediumblue"> </i>
                    </a>
                    <!-- Twitter -->
                    <a class="tw-ic btn btn-primary btn-lg btn-floating" style="background: white"
                       href="https://twitter.com/">
                        <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: mediumblue"> </i>
                    </a>
                    <!--Linkedin -->
                    <a class="li-ic btn btn-primary btn-lg btn-floating" style="background: white"
                       href="https://www.linkedin.com/">
                        <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"
                           style="color: mediumblue"> </i>
                    </a>
                    <!--Instagram-->
                    <a class="ins-ic btn btn-primary btn-lg btn-floating" style="background: white"
                       href="https://www.instagram.com/">
                        <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x" style="color: mediumblue"> </i>
                    </a>
                    <!--Pinterest-->
                    <a class="pin-ic btn btn-primary btn-lg btn-floating" style="background: white"
                       href="https://www.pinterest.com/">
                        <i class="fab fa-pinterest fa-lg white-text fa-2x" style="color: mediumblue"> </i>
                    </a>
                </div>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row-->
    </div>
    <!-- Footer Elements -->
    <!-- Copyright -->
    <div class="footer-copyright text-center py-2 text-white">© 2021 Copyright:
        <a href="https://primamealibrarie.net/" style="text-decoration: none">PRIMA MEA LIBRARIE.NET</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Checkout
{% endblock %}
{% block content %}
    <div class="container">
        <div class="jumbotron jumbotron-fluid">
            <h1>VA MULTUMIM PENTRU CA ATI VIZITAT SITE-UL NOSTRU SI VA ASTEPTAM ORICAND CU DRAG</h1>
        </div>
    </div>
{% endblock %}

templates/open_cart.html
{% extends 'base.html' %}
{% block title %}
    Cart
{% endblock %}
{% block content %}
    <div class="container-fluid text-center" style="margin-top:30px">
        <div class="container-fluid container-sm text-center">
            <h2 class="font-weight-bolder bg-info text-white p-1">CART</h2>
        </div>
        <div class="container-fluid container-sm text-center" style="margin-top:15px">
            <div class="row container-fluid container-sm text-center">
                <div class="col"><h3 class="font-weight-bolder bg-info text-white p-1">ITEM</h3></div>
                <div class="col"><h3 class="font-weight-bolder bg-info text-white p-1">PRICE</h3></div>
                <div class="col"><h3 class="font-weight-bolder bg-info text-white p-1">QUANTITY</h3></div>
                <div class="col"><h3 class="font-weight-bolder bg-info text-white p-1">ADD QUANTITY</h3></div>
            </div>
        </div>
        <br>
        <div class="container-fluid container-sm text-center">
            {% for cart_item in cart_items %}
                <div class="row container-fluid container-sm">
                    <div class="col">
                        <div>
                            <strong>{{ forloop.counter }}.</strong>
                            <img src="{{ cart_item.book.image.url }}" alt="" width="100" height="100">
                            <h4><strong>{{ cart_item.book.title }}</strong></h4>
                        </div>
                    </div>
                    <div class="col"><h4><strong>{{ cart_item.book.price }} lei</strong></h4></div>
                    <div class="col">
                        <div class="row justify-content-center">
                            <form method="post" action="{% url 'books:add_product_to_cart' %}">
                                {% csrf_token %}
                                <input type="hidden" name="book_id" value="{{ cart_item.book.id }}">
                                <input type="hidden" name="cantitate" value="-1">
                                <button class="font-weight-bolder btn btn-primary btn-lg m-1" type="submit">-</button>
                            </form>
                            <div class="large_text m-2">{{ cart_item.cantitate }}</div>
                            <form method="post" action="{% url 'books:add_product_to_cart' %}">
                                {% csrf_token %}
                                <input type="hidden" name="book_id" value="{{ cart_item.book.id }}">
                                <input type="hidden" name="cantitate" value="1">
                                <button class="font-weight-bolder btn btn-primary btn-lg m-1" type="submit">+</button>
                            </form>
                        </div>
                    </div>
                    <div class="col">
                        <form method="post" action="{% url 'books:add_product_to_cart' %}">
                            {% csrf_token %}
                            <input type="hidden" name="book_id" value="{{ cart_item.book.id }}">
                            <input type="number" name="cantitate" value="1" style="width:60px;">
                            <button class="font-weight-bolder btn btn-primary m-1" type="submit">ADD QUANTITY</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
            <div class="container-fluid container-sm text-center">
                <h3 class="font-weight-bolder bg-info text-white p-1">TOTAL:{{ total }} lei <i
                        class="fas fa-shopping-cart fa-lg"
                        style="color: white"></i><span
                        class="rounded-pill small font-weight-bolder"
                        style="background: white; color: #003366">  {{ count }}  </span></h3>
            </div>
            <br>
            <div class="container-fluid container-sm text-center">
                <form method="post" action="{% url 'books:checkout' %}">
                    {% csrf_token %}
                    <input type="hidden" name="cart_id" value="{{ open_cart.id }}">
                    <button class="font-weight-bolder btn btn-primary btn-lg m-1" type="submit">CHECKOUT</button>
                </form>
            </div>
            <br>
            <div class="p-3">
                <a href="{% url 'login' %}" class="btn btn-primary btn-lg">TO PAGE LOGIN</a>
                <a href="{% url 'logout' %}" class="btn btn-warning btn-lg">LOGOUT</a>
                <a href="{% url 'books:home_page' %}" class="btn btn-primary btn-lg">TO HOME PAGE</a>
            </div>
            <br>
        </div>
    </div>
{% endblock %}